# Generated by Django 5.2 on 2025-04-25 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Название пункта')),
                ('menu_name', models.CharField(max_length=100, verbose_name='Название меню')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка(URL) или именованная ссылка(named URL)')),
                ('named_url', models.CharField(blank=True, max_length=255, verbose_name='Именованная ссылка(named URL)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.treemenu', verbose_name='Пункт меню для ответвлений')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
