# Generated by Django 5.2 on 2025-04-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Название пункта')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.AlterField(
            model_name='treemenu',
            name='menu_name',
            field=models.CharField(help_text='Одинаковое название для всех меню одного дерева', max_length=100, verbose_name='Название меню'),
        ),
        migrations.AlterField(
            model_name='treemenu',
            name='name',
            field=models.CharField(help_text='Название пункта которое будет отображено на странице', max_length=75, verbose_name='Название пункта'),
        ),
    ]
